/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Vista;


import com.Controlador.controladorCliente;
import com.Modelo.Cliente;
import com.Modelo.Conexion;
import com.Modelo.ConsultaClientes;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Darwing Hernandez
 */
public class Registro extends javax.swing.JFrame {
    private Cliente cliente; // = new Cliente();
    private ConsultaClientes operacion;
    private controladorCliente controlador;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        //se le coloca titulo al formulario
        this.setTitle("Registrar Cliente");
        //Se sentra el formulario
        this.setLocationRelativeTo(this);
        //oculta del formulario el campo Id del formulario
        this.txtId.setVisible(false);
        construirTabla();

    }

    //Metodo para la matriz con la informaci[on de los objetos
    private String[][] obtenerMatriz(){
        //Se inicializa el controlador
        controlador = new controladorCliente();
        //Se crea el array donde se almacenaran los objetos obtenidos del controlador
        ArrayList<Cliente> clientes = (ArrayList<Cliente>) controlador.listarClientes();
        //se crea la matriz definiendo la cantida de filas y columnas
        String matrizInfo[][] = new String[clientes.size()][7];
        
        //se recorre el array y se va llenando la matriz
        for (int i = 0; i < clientes.size(); i++) {
            matrizInfo[i][0] = clientes.get(i).getId()+"";
            matrizInfo[i][1] = clientes.get(i).getCedula()+"";
            matrizInfo[i][2] = clientes.get(i).getNombre()+"";
            matrizInfo[i][3] = clientes.get(i).getDirecion()+"";
            matrizInfo[i][4] = clientes.get(i).getTelefono()+"";
            matrizInfo[i][5] = clientes.get(i).getCorreo()+"";
            matrizInfo[i][6] = clientes.get(i).getCargo()+"";
        }
        //retorna la matriz
      return matrizInfo;  
        
    }
    
    //Metodo para construir la Tabla con la informaci[on de la matriz construida anterior mente
    private void construirTabla(){
        //se inicializa la tabla
        tblTabla = new JTable();
        //se setea la tabla y s ele pasa la matriz que se lleno en el metodo obtenerMatriz() 
        //y el nombre de los titulos de las columnas
        tblTabla.setModel(new DefaultTableModel(
                obtenerMatriz(),
                new String[] {
                    "Id", "Cedula", "Nombre", "Direccion", "Telefono", "Correo", "Cargo"
                }
        ));
        scrollPanel.setViewportView(tblTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new org.edisoncor.gui.textField.TextField();
        txtCedula = new org.edisoncor.gui.textField.TextField();
        txtDireccion = new org.edisoncor.gui.textField.TextField();
        txtTelefono = new org.edisoncor.gui.textField.TextField();
        txtCorreo = new org.edisoncor.gui.textField.TextField();
        btnModificar = new rojeru_san.RSButtonRiple();
        btnGuardar = new rojeru_san.RSButtonRiple();
        btnBuscar = new rojeru_san.RSButtonRiple();
        txtBuscar = new org.edisoncor.gui.textField.TextField();
        jLabel8 = new javax.swing.JLabel();
        btnBorrar = new rojeru_san.RSButtonRiple();
        btnLimpiar = new rojeru_san.RSButtonRiple();
        jLabel9 = new javax.swing.JLabel();
        txtCargo = new org.edisoncor.gui.textField.TextField();
        txtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setColorPrimario(new java.awt.Color(102, 102, 102));
        panel1.setColorSecundario(new java.awt.Color(0, 102, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelShadow1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        panelShadow1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 155, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula");
        panelShadow1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 52, 155, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");
        panelShadow1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 156, 155, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono:");
        panelShadow1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 155, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar");
        panelShadow1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 90, 40));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelShadow1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 110, 433, 28));
        panelShadow1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 64, 433, 28));
        panelShadow1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 165, 433, 28));
        panelShadow1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 433, 28));
        panelShadow1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 433, 28));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelShadow1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 140, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelShadow1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 140, 40));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelShadow1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 140, 40));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        panelShadow1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 488, 490, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        panelShadow1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 155, 40));

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        panelShadow1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 140, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelShadow1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 140, 40));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cargo:");
        panelShadow1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 155, 40));
        panelShadow1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 433, 28));

        txtId.setEnabled(false);
        panelShadow1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 50, -1));

        jButton1.setText("listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelShadow1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre", "Direccion", "Telefono", "Correo", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel.setViewportView(tblTabla);

        panelShadow1.add(scrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 820, 100));

        panel1.add(panelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 860, 570));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        // Se almacenan en las variables la información tipeada en cada uno
        //de los campos del formulario        
        String ced = this.txtCedula.getText();
        String nom = this.txtNombre.getText();
        String dir = this.txtDireccion.getText();
        String tel = this.txtTelefono.getText();
        String correo = this.txtCorreo.getText();
        String cargo = this.txtCargo.getText();

        //se inicializa el modelo del objeto cliente
        cliente = new Cliente();
        
        //se crea el objeto Cliente, asiganadole la información tipeada por el 
        //usuario en el formulario
        cliente.setCedula(ced);
        cliente.setNombre(nom);
        cliente.setDirecion(dir);
        cliente.setTelefono(tel);
        cliente.setCorreo(correo);
        cliente.setCargo(cargo);
        
        //Se inicializa el controlador
        controlador = new controladorCliente();
        //se envia el objeto Cliente creado al metodo resgistrarCliente
        controlador.registrarCliente(cliente);
        construirTabla();
        
        
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Se almacenan en las variables la información tipeada en cada uno
        //de los campos del formulario       
        String ced = this.txtCedula.getText();
        String nom = this.txtNombre.getText();
        String dir = this.txtDireccion.getText();
        String tel = this.txtTelefono.getText();
        String correo = this.txtCorreo.getText();
        String cargo = this.txtCargo.getText();
        int id = Integer.parseInt(this.txtId.getText());
        
        //se inicializa el modelo del objeto cliente
        cliente = new Cliente();
        
        //se le asigana la información tipeada por el 
        //usuario en el formulario al objeto Cliente
        cliente.setCedula(ced);
        cliente.setNombre(nom);
        cliente.setDirecion(dir);
        cliente.setTelefono(tel);
        cliente.setCorreo(correo);
        cliente.setCargo(cargo);
        cliente.setId(id);
        
        //Se inicializa el controlador
        controlador = new controladorCliente();
        //se envia el objeto Cliente al metodo ActualizarCliente
        controlador.ActualizarCliente(cliente);
        construirTabla();
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Se guarda en la variable buscar la información tipeada en el campo buscar     
        String buscar = this.txtBuscar.getText();
        
        //Se valida que el campo no este vacio
        if (buscar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Buscar no puede estar vacio");
        }
        
        //Se inicaliza el objeto Cliente
        cliente = new Cliente();
        //se le asigna la infromación almacenada en la variable buscar a la 
        //variable cedula del objeto Cliente
        cliente.setCedula(buscar);
        
        //Se inicializa el controllador
        controlador = new controladorCliente();
        //enviamos al metodo buscar el objeto creado
        controlador.buscar(cliente);
        
        //asignamos la información obtenida del metodo buscar a cada uno de los 
        //campos del formulario
        this.txtCedula.setText(cliente.getCedula());
        this.txtNombre.setText(cliente.getNombre());
        this.txtDireccion.setText(cliente.getDirecion());
        this.txtTelefono.setText(cliente.getTelefono());
        this.txtCorreo.setText(cliente.getCorreo());
        this.txtCargo.setText(cliente.getCargo());
        this.txtId.setText(Integer.toString(cliente.getId()));
        
        
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // Se almacenan en las variables la información tipeada en cada uno
        //de los campos del formulario 
        String ced = this.txtCedula.getText();
        String nom = this.txtNombre.getText();
        String dir = this.txtDireccion.getText();
        String tel = this.txtTelefono.getText();
        String correo = this.txtCorreo.getText();
        String cargo = this.txtCargo.getText();
        String buscar = this.txtBuscar.getText();
        //Se inicializa el controllador
        controlador = new controladorCliente();
        
        
        //Se valida que los campos del formulario tengan infromación antes de borrar
        if (ced.isEmpty() && nom.isEmpty() && dir.isEmpty() && tel.isEmpty() && 
                correo.isEmpty() && cargo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe haber un Cliente cargado");
        }else
            //Se valida que el campo buscar tenga un texto para hacer la consulta antes de eliminar
            if (buscar.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El campo Buscar no puede estar vacio");
            }else{
                //enviamos al metodo buscar el objeto creado y valida si la respuesta recibida es true
                if(controlador.eliminarCliente(cliente)){
                    JOptionPane.showMessageDialog(null, "Cliente eliminado con Exito");
                }else
                    //muestra el mensaje en caso de que no se pueda eliminar el Cliente
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente");
            }
            
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // se setean todas los campos del formulario a vacio
        this.txtBuscar.setText("");
        this.txtCedula.setText("");
        this.txtNombre.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
        this.txtCorreo.setText("");
        this.txtCargo.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<Cliente> clientes = new ArrayList<>();
        
        
        
        controlador.listarClientes();
    }//GEN-LAST:event_jButton1ActionPerformed


     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.RSButtonRiple btnBorrar;
    public rojeru_san.RSButtonRiple btnBuscar;
    public rojeru_san.RSButtonRiple btnGuardar;
    public rojeru_san.RSButtonRiple btnLimpiar;
    public rojeru_san.RSButtonRiple btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tblTabla;
    public org.edisoncor.gui.textField.TextField txtBuscar;
    public org.edisoncor.gui.textField.TextField txtCargo;
    public org.edisoncor.gui.textField.TextField txtCedula;
    public org.edisoncor.gui.textField.TextField txtCorreo;
    public org.edisoncor.gui.textField.TextField txtDireccion;
    private javax.swing.JTextField txtId;
    public org.edisoncor.gui.textField.TextField txtNombre;
    public org.edisoncor.gui.textField.TextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
